import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "primereact/resources/themes/lara-light-indigo/theme.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Really simple NextJS demo</h1>
        <nav></nav>

        {children}
      </body>
    </html>
  )
}
